config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'shorten_urls#show'
  post '/create_url' => 'shorten_urls#create'
  get '/:url' => 'shorten_urls#fetch_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shorten_url.rb
class ShortenUrl < ApplicationRecord

  validate :check_url_validation

  after_validation :create_unique_key, :add_url_protocol

  # exclude records in which expiration time is greater then 5 days
  scope :unexpired, -> { where('created_at > ?', UrlShort.expiration_time) }


  # we'll check if provided url is valid or not
  def check_url_validation
    errors.add(:url, I18n.t('url_not_proper')) unless UrlShort.is_valid? (url)
  end

  # we'll rely on the DB to make sure the unique key is really unique.
  # if it isn't unique, the unique index will catch this and raise an error
  def create_unique_key
    begin
      self.unique_key = UrlShort.generate_key
    rescue ActiveRecord::RecordNotUnique
      if (count +=1) < 5
        retry
      else
        raise
      end
    end
  end

  # add protocol if not provided
  def add_url_protocol
    unless url[/\Ahttp:\/\//] || url[/\Ahttps:\/\//]
      self.url = "http://#{self.url}"
    end
  end

  # fetch the complete and shortened url
  def self.fetch_with_key(key, request)
    complete_url = ShortenUrl.unexpired.where(unique_key: key).first
    if complete_url
      short_url = merge_url(complete_url.unique_key, request)
      { url: complete_url.url, shortened_url: short_url }
    else
      nil
    end
  end

  # merge key with base url
  def self.merge_url(key, request)
    request + '/' + key
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shorten_urls_controller.rb
class ShortenUrlsController < ApplicationController

  def show
    @res = ShortenUrl.new
  end

  def create
    url = ShortenUrl.new(shorten_url_params)

    if url.save
      @res = ShortenUrl.fetch_with_key(url.unique_key, request.base_url)[:shortened_url] #fetch the url from database
    else
      @res = url.errors.full_messages.to_sentence
    end

    respond_to do |format|
      format.html
      format.js { render 'shorten_urls/shorten' }
    end
  end

  def fetch_page
    @res = ShortenUrl.fetch_with_key(params[:url], request.base_url)

    if @res
      redirect_to @res[:url] #if correct url redirect to given url
    else
      flash[:danger] = I18n.t('url_doesnt_exist')
      redirect_to root_path #if url not in database or expired redirect to root url
    end
  end

  private
  def shorten_url_params
    params.require(:shorten_url).permit(:url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shorten_urls_helper.rb
module ShortenUrlsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortenurl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">
          ShortenU
        </a>
      </div>
    </div>
  </nav>

  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= value %></div>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/shorten_urls/shorten.js.erb
$('#result_div').html('<%= @res %>');

app/views/shorten_urls/show.html.erb
<div class="container">

  <div class="heading-container">
    <h3>Insert Your URL Below</h3>
  </div>

  <div class="form-container">

    <%= form_for @res , url: create_url_path, remote: true  do |f|  %>

        <%= f.text_field :url, class: 'input-url' %>
        <%= f.submit "SHORTEN", class: 'btn btn-primary' %>

    <% end %>

    <div class="row result">
      <div id="result_div"></div>
    </div>

  </div>
</div>